### PR TITLE
Better support for multis with configurable channels

### PR DESCRIPTION
**Pull request by Lyfts**
Multiblocks with channels can now have each individual channel configured
br6343-channels

A button has been added to copy the channel configuration to a held hologram projector
br-copytoholo

And finally the project button has been made more responsive. Previously the button required the player to look at a block and gave no input if they weren't which understandably caused some confusion. 
Using the project button now will place the projection 2 blocks in front of the player if they aren't looking at a block. The bottom of the multiblock will always be placed on the chosen block so that multis with a controller above ground level won't have half their projection underground/obscured.

### CODE REVIEW

**Comment by AbdielKavash** [comment]
Would it be too difficult to make the channel-based selection, instead of being:

> Current channel: Glass
> << Channel >>
> << Current tier: 1 >>

to be:

> << Glass tier: 1 >>
> << Casing tier: 2 >>
> << Coil tier: 4 >>

where each of the individual values can be adjusted at the same time? IMO this would be a lot more intuitive, and also allow the player to see all the channels at once, without having to click through the menu,

**Comment by Lyfts** [comment]
I agree that would be nice but I deliberatly chose to implement it this way to avoid the buttons going off screen if a multi with a bunch of channels ever comes along. I have already had to scale the preview window based on gui scale in order to fit in the 3 lines I added. See
https://discord.com/channels/181078474394566657/603348502637969419/1236090652106821662

**Comment by AbdielKavash** [comment]
Would it be possible to put the configuration on the side then, instead of below the display?

**Comment by Lyfts** [comment]
It's possible yes but still gonna be a pain in the ass if any multi winds up with a lot of channels/long channel names. A side panel would have to dynamically scale on the x axis, adjust the font size or do line wraps, which would wind up causing space problems on the y axis instead, in order to accommodate longer channel names and do this while not colliding with the bookmark panel. 

A scrollable side panel or something of that sort could work but for now I'll let this feature stand on its merits and hope it motivates someone to implement a better solution for the gui.

For note this is the available real estate on auto gui scale on my monitor:
auto

**Comment by AbdielKavash** [comment]
In my opinion, the current implementation has the same unfinished / user-unfriendly / potentially confusing feeling that has been plaguing the NEI multiblock preview since the beginning. I don't feel comfortable approving it as it is. But also I do not want to reject it right away, as I think it is a good feature and the backend work is solid. But the UI/UX needs more work. I will leave it for other devs to share their comments.

**Review by mitchej123 — APPROVED** [review]
Seems like an improvement

**Pull request merged**
